// Slint toast component — C++ integration example.
//
// Demonstrates:
//   - Calling show() / hide() from C++
//   - Auto-dismiss via slint::Timer::single_shot
//   - Reacting to toast-closed and toast-action callbacks
//
// Build:
//   cmake -B build && cmake --build build
//   ./build/toast-example

#include "app.h"  // generated by slint_target_sources from ui/app.slint
#include <chrono>
#include <cstdio>

int main()
{
    auto ui = AppWindow::create();

    // Show a welcome toast on startup that auto-dismisses after 4 seconds.
    ui->invoke_show_toast(
        "Welcome! This toast will auto-dismiss in 4 seconds.",
        ToastKind::Info
    );

    slint::Timer::single_shot(std::chrono::milliseconds(4000), [ui]() {
        ui->invoke_hide_toast();
    });

    // React to the user manually closing the toast.
    // In a real app: cancel any pending dismiss timer here.
    ui->on_toast_closed([&]() {
        std::printf("Toast closed by user.\n");
    });

    // React to the action button.
    ui->on_toast_action([&]() {
        std::printf("Toast action triggered.\n");
    });

    ui->run();
    return 0;
}
